steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ussd-gateway:latest', './ussd_gateway']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ussd-gateway:latest']

images:
  - 'gcr.io/$PROJECT_ID/ussd-gateway:latest'
